services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: tweet_service
      POSTGRES_PASSWORD: tweet_service_pass
      POSTGRES_DB: tweet_service_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tweet_service"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: